import React from "react";
import Card from "./Card";

const Colors = () => {
  let colorData = [
    {
      english: "red",
      korean: "빨간색",
      imgSource:
        "https://htmlcolorcodes.com/assets/images/colors/red-color-solid-background-1920x1080.png",
    },
    {
      english: "blue",
      korean: "파란색",
      imgSource:
        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAKgAtAMBIgACEQEDEQH/xAAVAAEBAAAAAAAAAAAAAAAAAAAABP/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAWAQEBAQAAAAAAAAAAAAAAAAAABwb/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCUBvk8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/2Q==",
    },
    {
      english: "yellow",
      korean: "노란색",
      imgSource:
        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAKgAtAMBIgACEQEDEQH/xAAVAAEBAAAAAAAAAAAAAAAAAAAAB//EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAWAQEBAQAAAAAAAAAAAAAAAAAABwX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCmAI82AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/2Q==",
    },
    {
      english: "green",
      korean: "초록색",
      imgSource:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADACAMAAAB/Pny7AAAAD1BMVEUAmjHb2M739vQAjwDC3sVSWWqrAAAA4UlEQVR4nO3PCQ0AMAwAoe7xr3k2yHI4YNa+Zz5w7l5TBlRGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVGVUZVRlVG9V3mAf1PDwGvIXp9AAAAAElFTkSuQmCC",
    },
    {
      english: "black",
      korean: "검은색",
      imgSource:
        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAKgAtAMBIgACEQEDEQH/xAAVAAEBAAAAAAAAAAAAAAAAAAAAB//EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AhoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/Z",
    },
    {
      english: "white",
      korean: "하얀색",
      imgSource:
        "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBggIBw0HBwgICA0HBwcHBw8IDQcNIBEWFhURExoYKCggJBolGxMWITEhPT4rLi4uFx8zODMsNygtOisBCgoKDQ0NFg0PFi0lFh4tKysyLDArLTc3KzAtKysrNysrNysrKy0rNysrKys3KysrKysrLSsrKy0rKys3KzcrK//AABEIALkBEQMBIgACEQEDEQH/xAAYAAEBAQEBAAAAAAAAAAAAAAAAAQIHA//EAB4QAQEAAgICAwAAAAAAAAAAAAABAhEhMQNREkFh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGBEBAQEBAQAAAAAAAAAAAAAAABEhAgH/2gAMAwEAAhEDEQA/AO4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAAAAAAAAAAgAKAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAgAAKCKigAAAAAAAAlsnasZS28ctYzUEuqAKAAAAAAAAAAAAAAAAAAAAAAAAJsBFEBVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABKKggCigAAAAAAAAAAAAAAAAAAAAAAAAAAJQNqy0IACgAAAAACW6lvpUs3AYw8vyy116ejGPjmPW/wA39NjPNmgA0AAAAAAAAAAAAAAAAAAAAmlAAAAAAACs7WzcZ5GfW4JFGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2Q==",
    },
    {
      english: "orange",
      korean: "주황색",
      imgSource:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAA1BMVEX/rBwPUaadAAAAR0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8GxYgAAb0jQ/cAAAAASUVORK5CYII=",
    },
    {
      english: "purple",
      korean: "보라색",
      imgSource:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARMAAAC3CAMAAAAGjUrGAAAAOVBMVEWILPmLLvl4Iv98Jf15I/6KLfh/JvyEKvuDKfqBKPyAJ/uHK/qAJ/17JP96I/6CKvuMMPeEK/mCKProd1aeAAABWklEQVR4nO3QQQ6CMBRFURSsBQGV/S/WiiYUW+PY5Nz85L/xaW5bh7JTUVPtknV/dy6KectyfbWk+qwhK4xboaytNm3NXSq9tW7X8WsNEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJEyZMmDBhwoQJk78yqeCUJnWWryb3vGvMZowvkhWoHxPGOD6v70MYVqjUsJEMlUK7wvxwmrr5E2Xam3S79QBYmmegZYqPbQAAAABJRU5ErkJggg==",
    },
    {
      english: "pink",
      korean: "분홍색",
      imgSource:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAA1BMVEX4yNyQ69wLAAAAR0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8GxYgAAb0jQ/cAAAAASUVORK5CYII=",
    },
    {
      english: "brown",
      korean: "갈색",
      imgSource:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAA1BMVEXEpIQRYj2SAAAAR0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8GxYgAAb0jQ/cAAAAASUVORK5CYII=",
    },
    {
      english: "grey",
      korean: "회색",
      imgSource:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAA1BMVEWAgICQdD0xAAAAR0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8GxYgAAb0jQ/cAAAAASUVORK5CYII=",
    },
  ];
  return (
    <>
      {colorData.map((words) => {
        return <Card korean={words.korean} imgSource={words.imgSource} />;
      })}
    </>
  );
};

export default Colors;
